version: '3.4'

services:
  mainserverapp:
    image: ${DOCKER_REGISTRY-}mainserverapp
    build:
      context: .
      dockerfile: src/MainServerApp/Dockerfile

  secondserverapp:
    image: ${DOCKER_REGISTRY-}secondserverapp
    build:
      context: .
      dockerfile: src/SecondServerApp/Dockerfile

